runtime: java
env: flex

runtime_config:   # Optional
  jdk: openjdk8
  server: jetty9

automatic_scaling:
  max_num_instances: 1

# [START env_variables]
env_variables:    # Logging options
  JAVA_OPTS: >-
    -D.level=INFO

beta_settings:
  cloud_sql_instances: sequencegame:us-east4:seqgame=tcp:1433